POST http://localhost:3000/authentication/signin
Accept: application/json
Content-Type: application/json

{
    "email": "james@bond.com",
    "password": "strongpassword"
}

###

POST http://localhost:3000/authentication/signup
Accept: application/json
Content-Type: application/json

{
    "email": "james@bond.com",
    "firstName": "James",
    "lastName": "Bond",
    "password": "strongpassword"
}