GET http://localhost:3000/brands
Accept: application/json

###

GET http://localhost:3000/brands/04d3349d-9b05-43ec-8872-ebae59dd52c9
Accept: application/json

###

POST http://localhost:3000/brands
Accept: application/json
Content-Type: application/json

{
    "name": "Apple"
}

###

PUT http://localhost:3000/brands/04d3349d-9b05-43ec-8872-ebae59dd52c9
Accept: application/json
Content-Type: application/json

{
    "name": "Samsung"
}

###

DELETE http://localhost:3000/brands/04d3349d-9b05-43ec-8872-ebae59dd52c9
Accept: application/json